### ISSUE TITLE
Issue with Visualization in Tutorial: Heat Equation - Simple

### ISSUE THREAD

**Issue by guoran23** [AMReX-Codes/amrex-tutorials#111]
Description: 
I encountered a problem with the Visualization.ipynb notebook in the "Tutorial: Heat Equation - Simple." When attempting to use the `yt.SlicePlot` for visualization, it did not work as expected.

Steps taken:
1. Initially, I tried the following code:
   ```python
   import yt
   from yt.frontends.boxlib.data_structures import AMReXDataset
   ds = AMReXDataset("plt01000") 
   sl = yt.SlicePlot(ds, 2, ('boxlib', 'phi'))
   ```
   However, the `yt.SlicePlot` did not work as intended.

2. Subsequently, I attempted an alternative approach:
   ```python
   ds = yt.load("plt00000")
   sl = yt.SlicePlot(ds, 2, ('boxlib', 'phi'))
   ```
   While this did generate a slice plot, the x and y domains were not accurate.

Observations:
- Using `AMReXDataset("plt01000")` resulted in `ds` being recognized as an `AMRexDataset`.
- Conversely, using `yt.load("plt00000")` led to `ds` being identified as a `BoxlibDataset`.

Request:
I kindly ask for an update to the tutorial to ensure the visualization example works correctly. It seems that the choice of dataset loading method affects the type of dataset obtained, and this discrepancy impacts the accuracy of the visualization.

Thank you for your attention to this matter.

**Comment by atmyers** [comment]
Hi @guoran23,

I think this is due to some upstream changes in yt. Can you try adding the line `from yt.frontends import amrex` before `from yt.frontends.amrex.data_structures import AMReXDataset` and see if that fixes the issue for you?

-Andrew

**Comment by guoran23** [comment]
Hello Andrew, appreciate your quick response. 
I got the error message: 'ImportError: cannot import name 'amrex' from 'yt.frontends''. 
I am using yt version 4.3.0. 
I was looking at the yt cookbook, and currently, the data loading is done using `yt.load`. However, as mentioned earlier, when using `yt.load` to load the data and then creating a slice plot, the coordinate axes are not automatically set.

**Comment by atmyers** [comment]
Apologies, I should have said `boxlib` instead of `amrex`. Can you try the change here and see if it works for you?

https://github.com/AMReX-Codes/amrex-tutorials/pull/112

**Comment by guoran23** [comment]
The `yt.SlicePlot` is functioning now; however, the automatic configuration of x and y domains is incorrect. Ideally, it should be set to [0, 1], but currently, it is displaying [-0.5, 0.5].

**Comment by guoran23** [comment]
I'd like to clarify further. I've been trying the example in `/GuidedTutorials/HeatEquation_Simple/`, where the physical box is [0, 1]. The yt info I obtained also shows:

```
yt : [INFO     ] 2024-01-30 08:51:56,202 xlim = 0.000000 1.000000
yt : [INFO     ] 2024-01-30 08:51:56,203 ylim = 0.000000 1.000000
yt : [INFO     ] 2024-01-30 08:51:56,205 xlim = 0.000000 1.000000
yt : [INFO     ] 2024-01-30 08:51:56,206 ylim = 0.000000 1.000000
```
However, the plotted axes are incorrect [-0.5,0.5]. 
At the same time, I tried the ECP tutorials on Gitpod, and everything works well. I noticed that the `yt` version on Gitpod is `4.2.2`.
So it appears to be a potential issue with the `yt.SlicePlot` in version 4.3.0.

**Comment by atmyers** [comment]
This is the normal behavior of `SlicePlot`, which wants to center the coordinate system in the middle of the image (an astronomy convention...) I think you can override that by passing `origin='native'` as a keyword argument to `SlicePlot`.

**Comment by guoran23** [comment]
Thank you for your assistance. The two issues both have been successfully resolved.
