### ISSUE TITLE
Cavitation example

### ISSUE THREAD

**Issue by NiruBhai** [AMReX-Codes/amrex-tutorials#50]
Hello! I am a student currently doing a project on cavitation. I would like to know whether AMReX can be used to simulate phenomena like bubble collapse. If yes, could someone please upload a test case with code based on cavitation so that I can run and understand how AMReX can be used? I couldn't find any existing resources though I would be grateful if someone pointed them out.

Thanking you in advance,
Niranjan K. Sabu

**Comment by drummerdoc** [comment]
I suspect you'll need interface tracking code for multiphase bubble stuff.  There are various level-set implementation based on IAMR, but I am not aware of any quickie demo codes to demonstrate this.  Mark Sussman at Florida State has done a lot of work in this area for many years and could be one resource.  @asalmgren are there others that might be using more up-to-date AMReX distributions?

**Comment by NiruBhai** [comment]
> Hi Niranjan,
> 
> I suggest checking out the IAMR package, https://amrex-codes.github.io/IAMR/gallery.html the link to the docs is, https://amrex-codes.github.io/IAMR/docs_html/index.html. If you look in that repository you'll see there is a 2d test for bubble under `IAMR/Exec/run2d`. Is that what you're looking for?
> 
> Erik

Not exactly, but I got what I wanted. Thank you!
